/**
 * Trial period management — invite-based activation.
 *
 * Trials are NOT auto-activated on registration.
 * A trial invite code must be provided (generated by admin/sales).
 * This prevents abuse and allows controlled onboarding.
 */

import type { SubscriptionPlanId, TrialInvite } from "@/lib/iyzico/types";
import { createBrowserClient } from "@supabase/ssr";

// ─── Types ─────────────────────────────────────────────────────────────────────

interface TrialActivationResult {
  success: boolean;
  error?: string;
  trialEnd?: string;
}

interface TrialStatusResult {
  inTrial: boolean;
  trialDaysRemaining: number;
  trialEnd?: string;
  planName?: string;
}

// ─── Trial Invite Code Validation ──────────────────────────────────────────────

/**
 * Validate a trial invite code against Supabase.
 * Returns the invite details if valid and unused.
 */
export async function validateTrialInvite(
  code: string
): Promise<{ valid: boolean; invite?: TrialInvite; error?: string }> {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data: invite, error } = await supabase
    .from("trial_invites")
    .select("*")
    .eq("code", code.toUpperCase().trim())
    .is("used_by_tenant_id", null)
    .maybeSingle();

  if (error) {
    return { valid: false, error: "Sistem hatası. Lütfen tekrar deneyin." };
  }

  if (!invite) {
    return { valid: false, error: "Geçersiz veya kullanılmış davet kodu." };
  }

  if (new Date(invite.expires_at) < new Date()) {
    return { valid: false, error: "Davet kodu süresi dolmuş." };
  }

  return { valid: true, invite: invite as TrialInvite };
}

// ─── Trial Activation ──────────────────────────────────────────────────────────

/**
 * Activate a trial period for a tenant using an invite code.
 * Creates a subscription record with 'trial' status.
 */
export async function activateTrial(
  tenantId: string,
  inviteCode: string
): Promise<TrialActivationResult> {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  // 1. Validate invite
  const validation = await validateTrialInvite(inviteCode);
  if (!validation.valid || !validation.invite) {
    return { success: false, error: validation.error };
  }

  const invite = validation.invite;
  const now = new Date();
  const trialEnd = new Date(
    now.getTime() + invite.trial_days * 86400000
  );

  // 2. Check if tenant already has an active subscription
  const { data: existingSub } = await supabase
    .from("subscriptions")
    .select("id, status")
    .eq("tenant_id", tenantId)
    .in("status", ["active", "trial"])
    .maybeSingle();

  if (existingSub) {
    return { success: false, error: "Bu tesis zaten aktif bir aboneliğe sahip." };
  }

  // 3. Create trial subscription
  const { error: subError } = await supabase.from("subscriptions").insert({
    tenant_id: tenantId,
    plan_id: invite.plan_id,
    status: "trial",
    trial_start: now.toISOString(),
    trial_end: trialEnd.toISOString(),
    current_period_start: now.toISOString(),
    current_period_end: trialEnd.toISOString(),
  });

  if (subError) {
    return { success: false, error: "Deneme süresi başlatılamadı." };
  }

  // 4. Mark invite as used
  const { error: inviteError } = await supabase
    .from("trial_invites")
    .update({
      used_by_tenant_id: tenantId,
      used_at: now.toISOString(),
    })
    .eq("id", invite.id);

  if (inviteError) {
    console.error("Failed to mark invite as used:", inviteError);
    // Non-critical — subscription is already created
  }

  return {
    success: true,
    trialEnd: trialEnd.toISOString(),
  };
}

// ─── Trial Status ──────────────────────────────────────────────────────────────

/**
 * Get the current trial status for a tenant.
 */
export async function getTrialStatus(
  tenantId: string
): Promise<TrialStatusResult> {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data: sub } = await supabase
    .from("subscriptions")
    .select("*")
    .eq("tenant_id", tenantId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!sub || sub.status !== "trial") {
    return { inTrial: false, trialDaysRemaining: 0 };
  }

  const now = new Date();
  const trialEnd = new Date(sub.trial_end);
  const remainingMs = trialEnd.getTime() - now.getTime();
  const remainingDays = Math.max(0, Math.ceil(remainingMs / 86400000));

  return {
    inTrial: remainingDays > 0,
    trialDaysRemaining: remainingDays,
    trialEnd: sub.trial_end,
    planName: sub.plan_id,
  };
}
