// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ab-test" | "/ai" | "/analytics" | "/analytics/conversion" | "/analytics/revenue" | "/apart" | "/blog" | "/blog/[slug]" | "/dashboard" | "/feedback" | "/humanization" | "/login" | "/messages" | "/onboarding" | "/otel" | "/payments" | "/referral" | "/reports" | "/reservation-action" | "/reservations" | "/settings" | "/settings/billing/bank-accounts" | "/settings/channels" | "/settings/facilities" | "/signup" | "/subscription" | "/villa" | "/whatsapp" | "/widget"
type AppRouteHandlerRoutes = "/api/ab-test/auto-optimize" | "/api/analytics/pricing-optimization" | "/api/analytics/revenue-forecast" | "/api/channels/messenger" | "/api/channels/telegram" | "/api/feedback" | "/api/health" | "/api/settings/bank-accounts" | "/api/webhooks/iban-payment"
type PageRoutes = never
type LayoutRoutes = "/" | "/widget"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/ab-test": {}
  "/ai": {}
  "/analytics": {}
  "/analytics/conversion": {}
  "/analytics/revenue": {}
  "/apart": {}
  "/api/ab-test/auto-optimize": {}
  "/api/analytics/pricing-optimization": {}
  "/api/analytics/revenue-forecast": {}
  "/api/channels/messenger": {}
  "/api/channels/telegram": {}
  "/api/feedback": {}
  "/api/health": {}
  "/api/settings/bank-accounts": {}
  "/api/webhooks/iban-payment": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/dashboard": {}
  "/feedback": {}
  "/humanization": {}
  "/login": {}
  "/messages": {}
  "/onboarding": {}
  "/otel": {}
  "/payments": {}
  "/referral": {}
  "/reports": {}
  "/reservation-action": {}
  "/reservations": {}
  "/settings": {}
  "/settings/billing/bank-accounts": {}
  "/settings/channels": {}
  "/settings/facilities": {}
  "/signup": {}
  "/subscription": {}
  "/villa": {}
  "/whatsapp": {}
  "/widget": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/widget": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
